language: node_js
node_js:
  - 14

cache:
  directories:
    - node_modules

install:
  - yarn install --production

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
